"""Phase 3C Capability Registry — Static Manifest (single source of truth).

This module is the **static manifest**: a tracked, reviewable, deterministic
data structure that declares every capability the dev instance knows about.

Hard guarantees (frozen):

  - **Static.** A literal Python tuple of dicts. No runtime plugin path, no
    ``importlib``, no path-based file load, no remote fetch.
  - **Deterministic.** Same source → same registry output. No ``Date.now()`` /
    wall-clock sampling: ``CREATED_AT`` / ``UPDATED_AT`` are pinned constants.
  - **No execution surface.** No entry carries a forbidden field
    (``pythonImportPath``, ``callable``, ``shellCommand``, ``externalUrl``,
    ``downloadUrl``, ``pluginPackage``, ``dynamicModule``, ``evalCode``,
    ``execCode``, ``sqlStatement``, ``productionPath``, ``apiKey``,
    ``Authorization``, ``secret``). The registry describes capabilities; it
    never invokes them.
  - **Dev-only.** Every entry has ``devOnly = True`` and
    ``productionAllowed = False``.

The manifest is loaded by :mod:`hermes_cli.dev_web_capability_registry`, which
validates it before exposing anything. Loading the manifest never performs a
side effect.

Phase: 3C — Static dev-only Capability Registry
Status: implemented
"""

from __future__ import annotations

from typing import Any

#: Frozen manifest version. Bumped only under an authorized scope freeze.
MANIFEST_VERSION: str = "phase3c-static-v1"

#: Pinned creation / update timestamps (NOT wall-clock derived). The manifest
#: is deterministic; the registry loader never samples the clock.
CREATED_AT: str = "2026-06-17T00:00:00Z"
UPDATED_AT: str = "2026-06-17T00:00:00Z"

#: The static manifest. Each entry is a plain dict. Field set is validated
#: against :mod:`hermes_cli.dev_web_capability_registry_schema`. Ordering is
#: deterministic (registry, tool, sandbox, provider, workflow, forbidden) and
#: stable across loads.
STATIC_CAPABILITY_MANIFEST: tuple[dict[str, Any], ...] = (
    # ── 8.1 Registry capabilities (the registry describes itself) ──────────
    {
        "capabilityId": "registry.capability_registry_status",
        "displayName": "Capability Registry Status",
        "description": "Read-only registry summary surfaced under the existing /status block.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "capability_registry_",
        "metadataSchema": "registry_status_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "registry.capability_registry_list",
        "displayName": "Capability Registry List",
        "description": "Read-only enumeration of declared capabilities (in-process, no new route).",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "DEV_STATIC_MANIFEST",
        "executionMode": "read_only",
        "routeExposure": "no_route",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "capability_registry_",
        "metadataSchema": "registry_list_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "registry.capability_registry_detail",
        "displayName": "Capability Registry Detail",
        "description": "Read-only safe record for a single declared capability.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "DEV_STATIC_MANIFEST",
        "executionMode": "read_only",
        "routeExposure": "no_route",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "capability_registry_",
        "metadataSchema": "registry_detail_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "registry.capability_registry_audit",
        "displayName": "Capability Registry Audit",
        "description": "Redacted capability_registry_* audit breadcrumb emission (safe fields only).",
        "category": "audit",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "no_route",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "capability_registry_",
        "metadataSchema": "registry_audit_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    # ── 8.2 Read-only tool capabilities ───────────────────────────────────
    {
        "capabilityId": "tool.read.clarify",
        "displayName": "Clarify (read-only)",
        "description": "Read-only clarify handoff dispatched through the controlled-execution chain.",
        "category": "tool",
        "version": MANIFEST_VERSION,
        "owner": "phase-1g",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "clarify",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "tool_clarify_",
        "metadataSchema": "tool_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.read.tool_policy_read",
        "displayName": "Tool Policy Read",
        "description": "Read-only tool policy / catalog / schema exposure (GET routes only).",
        "category": "tool",
        "version": MANIFEST_VERSION,
        "owner": "phase-1g",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "tool_policy_read",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "tool_policy_",
        "metadataSchema": "tool_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.read.route_governance_read",
        "displayName": "Route Governance Read",
        "description": "Read-only frozen route-governance baseline (OpenAPI 34 / runtime 34 / 5/0/1/1).",
        "category": "system",
        "version": MANIFEST_VERSION,
        "owner": "phase-2e",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "route_governance_read",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "route_governance_",
        "metadataSchema": "system_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.read.audit_events_read",
        "displayName": "Audit Events Read",
        "description": "Read-only query of the dev durable audit store (no mutation).",
        "category": "audit",
        "version": MANIFEST_VERSION,
        "owner": "phase-2d",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "audit_events_read",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "audit_events_",
        "metadataSchema": "audit_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.read.dev_environment_read",
        "displayName": "Dev Environment Read",
        "description": "Read-only dev environment / isolation verification.",
        "category": "system",
        "version": MANIFEST_VERSION,
        "owner": "phase-2e",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_environment_read",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "dev_environment_",
        "metadataSchema": "system_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.read.release_status_read",
        "displayName": "Release Status Read",
        "description": "Read-only sealed phase timeline / release status.",
        "category": "system",
        "version": MANIFEST_VERSION,
        "owner": "phase-2e",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "release_status_read",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "release_status_",
        "metadataSchema": "system_read_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    # ── 8.3 Sandbox write-preview / write-confirm capabilities ────────────
    {
        "capabilityId": "tool.sandbox.dev_sandbox_file_write",
        "displayName": "Dev Sandbox File Write",
        "description": "Dev-sandbox file write requiring dry-run + digest + confirmation token + audit.",
        "category": "sandbox",
        "version": MANIFEST_VERSION,
        "owner": "phase-2c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "WRITE_CONFIRM",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "confirmed_execute",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_sandbox_file_write",
        "requiresApproval": True,
        "requiresDryRun": True,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "sandbox_write_",
        "metadataSchema": "sandbox_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.sandbox.dev_sandbox_file_append",
        "displayName": "Dev Sandbox File Append",
        "description": "Dev-sandbox file append requiring dry-run + digest + confirmation token + audit.",
        "category": "sandbox",
        "version": MANIFEST_VERSION,
        "owner": "phase-2c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "WRITE_CONFIRM",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "confirmed_execute",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_sandbox_file_append",
        "requiresApproval": True,
        "requiresDryRun": True,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "sandbox_append_",
        "metadataSchema": "sandbox_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.sandbox.dev_sandbox_file_patch",
        "displayName": "Dev Sandbox File Patch",
        "description": "Dev-sandbox file patch requiring dry-run + digest + confirmation token + audit.",
        "category": "sandbox",
        "version": MANIFEST_VERSION,
        "owner": "phase-2c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "WRITE_CONFIRM",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "confirmed_execute",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_sandbox_file_patch",
        "requiresApproval": True,
        "requiresDryRun": True,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "sandbox_patch_",
        "metadataSchema": "sandbox_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.sandbox.dev_sandbox_file_readback",
        "displayName": "Dev Sandbox File Readback",
        "description": "Dev-sandbox file read-back after a confirmed write (read-only verification).",
        "category": "sandbox",
        "version": MANIFEST_VERSION,
        "owner": "phase-2c",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_sandbox_file_readback",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "sandbox_readback_",
        "metadataSchema": "sandbox_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "tool.sandbox.dev_sandbox_rollback_execute",
        "displayName": "Dev Sandbox Rollback Execute",
        "description": "Dev-sandbox rollback requiring a rollback manifest + explicit confirmation + audit.",
        "category": "sandbox",
        "version": MANIFEST_VERSION,
        "owner": "phase-2c-h1",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "ROLLBACK_CONFIRM",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "confirmed_execute",
        "routeExposure": "existing_route_only",
        "toolBinding": "dev_sandbox_rollback_execute",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "sandbox_rollback_",
        "metadataSchema": "sandbox_rollback_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    # ── 8.4 Provider capabilities ─────────────────────────────────────────
    {
        "capabilityId": "provider.fake_roundtrip",
        "displayName": "Provider Fake Round-trip",
        "description": "Deterministic offline provider round-trip (no network, no real key).",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-2b",
        "source": "builtin",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "providerBinding": "fake",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "provider_fake_",
        "metadataSchema": "provider_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.real_boundary_status",
        "displayName": "Provider Real Boundary Status",
        "description": "Read-only real-provider boundary safe-metadata (value-free; no network call).",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "providerBinding": "real_boundary",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "provider_boundary_",
        "metadataSchema": "provider_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.real_request_preview",
        "displayName": "Provider Real Request Preview",
        "description": "Read-only preview of the real-provider request shape (no network call, no key value).",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "dry_run",
        "routeExposure": "existing_route_only",
        "providerBinding": "real_boundary",
        "requiresApproval": False,
        "requiresDryRun": True,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "provider_preview_",
        "metadataSchema": "provider_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.real_gated_roundtrip",
        "displayName": "Provider Real Gated Round-trip",
        "description": "Real provider round-trip gated by approval + budget + kill switch + audit (disabled by default).",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "disabled",
        "permissionClass": "LIVE_PROVIDER_GATED",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "manual_live",
        "routeExposure": "existing_route_only",
        "providerBinding": "real_gated",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": True,
        "requiresKillSwitch": True,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "auditEventPrefix": "provider_real_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.live_manual_one_shot",
        "displayName": "Provider Live Manual One-shot",
        "description": "Strict manual single-use live provider gate (listed only; not executed in the first version).",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b-live",
        "source": "provider_boundary",
        "status": "disabled",
        "permissionClass": "LIVE_PROVIDER_GATED",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "manual_live",
        "routeExposure": "existing_route_only",
        "providerBinding": "live_manual_one_shot",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": True,
        "requiresKillSwitch": True,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "auditEventPrefix": "provider_live_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.tool_call_classification",
        "displayName": "Provider Tool-call Classification",
        "description": "Read-only classification of a provider tool call against the live tool allowlist.",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "providerBinding": "tool_call_classification",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "provider_toolcall_",
        "metadataSchema": "provider_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.tool_execution",
        "displayName": "Provider Tool Execution",
        "description": "Provider-side tool execution. Forbidden in the first live path.",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b-live",
        "source": "provider_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "providerBinding": "tool_execution",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": True,
        "requiresKillSwitch": True,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_tool_execution_blocked_in_first_live_path",
        "auditEventPrefix": "provider_tool_exec_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.write",
        "displayName": "Provider Write",
        "description": "Provider write. Permanently forbidden.",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "providerBinding": "write",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_write_forbidden",
        "auditEventPrefix": "provider_write_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.auto_write",
        "displayName": "Provider Auto-write",
        "description": "Autonomous provider write. Permanently forbidden.",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "providerBinding": "auto_write",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_auto_write_forbidden",
        "auditEventPrefix": "provider_autowrite_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "provider.autonomous_action",
        "displayName": "Provider Autonomous Action",
        "description": "Autonomous provider action without human approval. Permanently forbidden.",
        "category": "provider",
        "version": MANIFEST_VERSION,
        "owner": "phase-3b",
        "source": "provider_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "providerBinding": "autonomous_action",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_autonomous_action_forbidden",
        "auditEventPrefix": "provider_autonomous_",
        "metadataSchema": "provider_live_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    # ── 8.5 Workflow capabilities ─────────────────────────────────────────
    {
        "capabilityId": "workflow.step.read_only_tool",
        "displayName": "Workflow Step — Read-only Tool",
        "description": "Workflow step binding a read-only tool.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "workflowBinding": "read_only_tool",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.step.fake_provider_roundtrip",
        "displayName": "Workflow Step — Fake Provider Round-trip",
        "description": "Workflow step binding the deterministic fake provider round-trip.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "workflowBinding": "fake_provider_roundtrip",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.step.sandbox_write_preview",
        "displayName": "Workflow Step — Sandbox Write Preview",
        "description": "Workflow step generating a sandbox write preview only (no real write).",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "WRITE_PREVIEW",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "dry_run",
        "routeExposure": "existing_route_only",
        "workflowBinding": "sandbox_write_preview",
        "requiresApproval": False,
        "requiresDryRun": True,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.step.rollback_reference",
        "displayName": "Workflow Step — Rollback Reference",
        "description": "Workflow step referencing a rollback manifest (read-only reference).",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "workflowBinding": "rollback_reference",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.step.manual_note",
        "displayName": "Workflow Step — Manual Note",
        "description": "Workflow step carrying a manual operator note (read-only).",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "workflowBinding": "manual_note",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.step.audit_query",
        "displayName": "Workflow Step — Audit Query",
        "description": "Workflow step performing a read-only audit query.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a",
        "source": "workflow_boundary",
        "status": "enabled",
        "permissionClass": "READ_ONLY",
        "trustLevel": "BUILTIN_VERIFIED",
        "executionMode": "read_only",
        "routeExposure": "existing_route_only",
        "workflowBinding": "audit_query",
        "requiresApproval": False,
        "requiresDryRun": False,
        "requiresConfirmation": False,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": False,
        "auditEventPrefix": "workflow_step_",
        "metadataSchema": "workflow_step_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.write_execute",
        "displayName": "Workflow Write Execute",
        "description": "Workflow write execution. Requires separate authorization; not executable until authorized.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "blocked",
        "permissionClass": "WRITE_CONFIRM",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "workflowBinding": "write_execute",
        "requiresApproval": True,
        "requiresDryRun": True,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "workflow_write_execute_requires_separate_authorization",
        "auditEventPrefix": "workflow_write_",
        "metadataSchema": "workflow_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.rollback_execute",
        "displayName": "Workflow Rollback Execute",
        "description": "Workflow rollback execution. Requires separate authorization; not executable until authorized.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "blocked",
        "permissionClass": "ROLLBACK_CONFIRM",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "workflowBinding": "rollback_execute",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "workflow_rollback_execute_requires_separate_authorization",
        "auditEventPrefix": "workflow_rollback_",
        "metadataSchema": "workflow_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.auto_advance",
        "displayName": "Workflow Auto-advance",
        "description": "Autonomous workflow step auto-advancement. Permanently forbidden.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "workflowBinding": "auto_advance",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "workflow_auto_advance_forbidden",
        "auditEventPrefix": "workflow_autoadvance_",
        "metadataSchema": "workflow_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.autonomous_write",
        "displayName": "Workflow Autonomous Write",
        "description": "Autonomous workflow write without human approval. Permanently forbidden.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "workflowBinding": "autonomous_write",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "workflow_autonomous_write_forbidden",
        "auditEventPrefix": "workflow_autonomous_",
        "metadataSchema": "workflow_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "workflow.background_schedule",
        "displayName": "Workflow Background Schedule",
        "description": "Background / unsupervised workflow scheduling. Permanently forbidden.",
        "category": "workflow",
        "version": MANIFEST_VERSION,
        "owner": "phase-3a-h1",
        "source": "workflow_boundary",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXPERIMENTAL_DISABLED",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "workflowBinding": "background_schedule",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "workflow_background_schedule_forbidden",
        "auditEventPrefix": "workflow_background_",
        "metadataSchema": "workflow_write_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    # ── 8.6 Forbidden capabilities (described + blocked; never executed) ──
    {
        "capabilityId": "capability.forbidden.dynamic_plugin_load",
        "displayName": "Forbidden — Dynamic Plugin Load",
        "description": "Dynamic plugin / importlib / path-based code loading. Described as blocked; never loaded.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "EXTERNAL_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "dynamic_plugin_load_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.remote_registry",
        "displayName": "Forbidden — Remote Registry",
        "description": "Remote registry / remote manifest fetch. Described as blocked; never fetched.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "EXTERNAL_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "remote_registry_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.marketplace",
        "displayName": "Forbidden — Marketplace",
        "description": "Plugin marketplace. Described as blocked; never reachable.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "EXTERNAL_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "marketplace_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.shell",
        "displayName": "Forbidden — Shell",
        "description": "Shell-command capability. Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "shell_command_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.database_mutation",
        "displayName": "Forbidden — Database Mutation",
        "description": "Database mutation capability. Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "database_mutation_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.external_http",
        "displayName": "Forbidden — External HTTP",
        "description": "External HTTP capability. Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "EXTERNAL_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "external_http_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.production_operation",
        "displayName": "Forbidden — Production Operation",
        "description": "Production operation against the production home or production database. Described as blocked; never reached.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "PRODUCTION_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "production_operation_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.provider_write",
        "displayName": "Forbidden — Provider Write",
        "description": "Provider write (alias declaration). Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_write_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.provider_auto_write",
        "displayName": "Forbidden — Provider Auto-write",
        "description": "Provider auto-write (alias declaration). Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "provider_auto_write_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
    {
        "capabilityId": "capability.forbidden.autonomous_write",
        "displayName": "Forbidden — Autonomous Write",
        "description": "Autonomous write (alias declaration). Described as blocked; never executed.",
        "category": "registry",
        "version": MANIFEST_VERSION,
        "owner": "phase-3c",
        "source": "static_manifest",
        "status": "blocked",
        "permissionClass": "ADMIN_FORBIDDEN",
        "trustLevel": "EXTERNAL_FORBIDDEN",
        "executionMode": "none",
        "routeExposure": "forbidden_new_route",
        "requiresApproval": True,
        "requiresDryRun": False,
        "requiresConfirmation": True,
        "requiresAudit": True,
        "requiresBudget": False,
        "requiresKillSwitch": False,
        "devOnly": True,
        "productionAllowed": False,
        "disabledByDefault": True,
        "blockedReason": "autonomous_write_forbidden",
        "auditEventPrefix": "capability_forbidden_",
        "metadataSchema": "forbidden_v1",
        "createdAt": CREATED_AT,
        "updatedAt": UPDATED_AT,
    },
)


def get_static_manifest() -> tuple[dict[str, Any], ...]:
    """Return the frozen static manifest (a fresh tuple reference).

    The manifest is immutable; callers must not mutate entries. The registry
    loader copies the safe fields it exposes.
    """
    return STATIC_CAPABILITY_MANIFEST


__all__ = [
    "MANIFEST_VERSION",
    "CREATED_AT",
    "UPDATED_AT",
    "STATIC_CAPABILITY_MANIFEST",
    "get_static_manifest",
]
