/**
 * Frozen static Capability Registry manifest — Phase 3C (frontend mirror).
 *
 * This is a tracked, reviewable, deterministic mirror of the backend static
 * manifest (hermes_cli/dev_web_capability_registry_manifest.py). It carries
 * ONLY safe, value-free fields — no API key, Authorization, Bearer, secret,
 * callable repr, shell command, SQL statement, production path, local plugin
 * path, dynamic import path, or external URL.
 *
 * The authoritative runtime validation status + counts come from the live
 * GET /status data.capabilityRegistry block; this constant provides the
 * read-only list + detail (no new HTTP route is introduced). The registry
 * describes capabilities only — it never grants permission.
 */

import type { CapabilityDetail } from '@/types/api/capabilityRegistry'

export const CAPABILITY_REGISTRY_VERSION = "phase3c-static-v1"

export const CAPABILITY_REGISTRY_MANIFEST: readonly CapabilityDetail[] = [
  {"capabilityId": "registry.capability_registry_status", "displayName": "Capability Registry Status", "description": "Read-only registry summary surfaced under the existing /status block.", "category": "registry", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "auditEventPrefix": "capability_registry_", "metadataSchema": "registry_status_v1", "redactionApplied": true},
  {"capabilityId": "registry.capability_registry_list", "displayName": "Capability Registry List", "description": "Read-only enumeration of declared capabilities (in-process, no new route).", "category": "registry", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "DEV_STATIC_MANIFEST", "executionMode": "read_only", "routeExposure": "no_route", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "auditEventPrefix": "capability_registry_", "metadataSchema": "registry_list_v1", "redactionApplied": true},
  {"capabilityId": "registry.capability_registry_detail", "displayName": "Capability Registry Detail", "description": "Read-only safe record for a single declared capability.", "category": "registry", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "DEV_STATIC_MANIFEST", "executionMode": "read_only", "routeExposure": "no_route", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "auditEventPrefix": "capability_registry_", "metadataSchema": "registry_detail_v1", "redactionApplied": true},
  {"capabilityId": "registry.capability_registry_audit", "displayName": "Capability Registry Audit", "description": "Redacted capability_registry_* audit breadcrumb emission (safe fields only).", "category": "audit", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "no_route", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "auditEventPrefix": "capability_registry_", "metadataSchema": "registry_audit_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.clarify", "displayName": "Clarify (read-only)", "description": "Read-only clarify handoff dispatched through the controlled-execution chain.", "category": "tool", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "clarify", "auditEventPrefix": "tool_clarify_", "metadataSchema": "tool_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.tool_policy_read", "displayName": "Tool Policy Read", "description": "Read-only tool policy / catalog / schema exposure (GET routes only).", "category": "tool", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "tool_policy_read", "auditEventPrefix": "tool_policy_", "metadataSchema": "tool_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.route_governance_read", "displayName": "Route Governance Read", "description": "Read-only frozen route-governance baseline (OpenAPI 34 / runtime 34 / 5/0/1/1).", "category": "system", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "route_governance_read", "auditEventPrefix": "route_governance_", "metadataSchema": "system_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.audit_events_read", "displayName": "Audit Events Read", "description": "Read-only query of the dev durable audit store (no mutation).", "category": "audit", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "audit_events_read", "auditEventPrefix": "audit_events_", "metadataSchema": "audit_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.dev_environment_read", "displayName": "Dev Environment Read", "description": "Read-only dev environment / isolation verification.", "category": "system", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_environment_read", "auditEventPrefix": "dev_environment_", "metadataSchema": "system_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.read.release_status_read", "displayName": "Release Status Read", "description": "Read-only sealed phase timeline / release status.", "category": "system", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "release_status_read", "auditEventPrefix": "release_status_", "metadataSchema": "system_read_v1", "redactionApplied": true},
  {"capabilityId": "tool.sandbox.dev_sandbox_file_write", "displayName": "Dev Sandbox File Write", "description": "Dev-sandbox file write requiring dry-run + digest + confirmation token + audit.", "category": "sandbox", "status": "enabled", "permissionClass": "WRITE_CONFIRM", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "confirmed_execute", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": true, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_sandbox_file_write", "auditEventPrefix": "sandbox_write_", "metadataSchema": "sandbox_write_v1", "redactionApplied": true},
  {"capabilityId": "tool.sandbox.dev_sandbox_file_append", "displayName": "Dev Sandbox File Append", "description": "Dev-sandbox file append requiring dry-run + digest + confirmation token + audit.", "category": "sandbox", "status": "enabled", "permissionClass": "WRITE_CONFIRM", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "confirmed_execute", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": true, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_sandbox_file_append", "auditEventPrefix": "sandbox_append_", "metadataSchema": "sandbox_write_v1", "redactionApplied": true},
  {"capabilityId": "tool.sandbox.dev_sandbox_file_patch", "displayName": "Dev Sandbox File Patch", "description": "Dev-sandbox file patch requiring dry-run + digest + confirmation token + audit.", "category": "sandbox", "status": "enabled", "permissionClass": "WRITE_CONFIRM", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "confirmed_execute", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": true, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_sandbox_file_patch", "auditEventPrefix": "sandbox_patch_", "metadataSchema": "sandbox_write_v1", "redactionApplied": true},
  {"capabilityId": "tool.sandbox.dev_sandbox_file_readback", "displayName": "Dev Sandbox File Readback", "description": "Dev-sandbox file read-back after a confirmed write (read-only verification).", "category": "sandbox", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_sandbox_file_readback", "auditEventPrefix": "sandbox_readback_", "metadataSchema": "sandbox_write_v1", "redactionApplied": true},
  {"capabilityId": "tool.sandbox.dev_sandbox_rollback_execute", "displayName": "Dev Sandbox Rollback Execute", "description": "Dev-sandbox rollback requiring a rollback manifest + explicit confirmation + audit.", "category": "sandbox", "status": "enabled", "permissionClass": "ROLLBACK_CONFIRM", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "confirmed_execute", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "toolBinding": "dev_sandbox_rollback_execute", "auditEventPrefix": "sandbox_rollback_", "metadataSchema": "sandbox_rollback_v1", "redactionApplied": true},
  {"capabilityId": "provider.fake_roundtrip", "displayName": "Provider Fake Round-trip", "description": "Deterministic offline provider round-trip (no network, no real key).", "category": "provider", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "providerBinding": "fake", "auditEventPrefix": "provider_fake_", "metadataSchema": "provider_v1", "redactionApplied": true},
  {"capabilityId": "provider.real_boundary_status", "displayName": "Provider Real Boundary Status", "description": "Read-only real-provider boundary safe-metadata (value-free; no network call).", "category": "provider", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "providerBinding": "real_boundary", "auditEventPrefix": "provider_boundary_", "metadataSchema": "provider_v1", "redactionApplied": true},
  {"capabilityId": "provider.real_request_preview", "displayName": "Provider Real Request Preview", "description": "Read-only preview of the real-provider request shape (no network call, no key value).", "category": "provider", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "dry_run", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": true, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "providerBinding": "real_boundary", "auditEventPrefix": "provider_preview_", "metadataSchema": "provider_v1", "redactionApplied": true},
  {"capabilityId": "provider.real_gated_roundtrip", "displayName": "Provider Real Gated Round-trip", "description": "Real provider round-trip gated by approval + budget + kill switch + audit (disabled by default).", "category": "provider", "status": "disabled", "permissionClass": "LIVE_PROVIDER_GATED", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "manual_live", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": true, "requiresKillSwitch": true, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": null, "providerBinding": "real_gated", "auditEventPrefix": "provider_real_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "provider.live_manual_one_shot", "displayName": "Provider Live Manual One-shot", "description": "Strict manual single-use live provider gate (listed only; not executed in the first version).", "category": "provider", "status": "disabled", "permissionClass": "LIVE_PROVIDER_GATED", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "manual_live", "routeExposure": "existing_route_only", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": true, "requiresKillSwitch": true, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": null, "providerBinding": "live_manual_one_shot", "auditEventPrefix": "provider_live_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "provider.tool_call_classification", "displayName": "Provider Tool-call Classification", "description": "Read-only classification of a provider tool call against the live tool allowlist.", "category": "provider", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "providerBinding": "tool_call_classification", "auditEventPrefix": "provider_toolcall_", "metadataSchema": "provider_v1", "redactionApplied": true},
  {"capabilityId": "provider.tool_execution", "displayName": "Provider Tool Execution", "description": "Provider-side tool execution. Forbidden in the first live path.", "category": "provider", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": true, "requiresKillSwitch": true, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_tool_execution_blocked_in_first_live_path", "providerBinding": "tool_execution", "auditEventPrefix": "provider_tool_exec_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "provider.write", "displayName": "Provider Write", "description": "Provider write. Permanently forbidden.", "category": "provider", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_write_forbidden", "providerBinding": "write", "auditEventPrefix": "provider_write_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "provider.auto_write", "displayName": "Provider Auto-write", "description": "Autonomous provider write. Permanently forbidden.", "category": "provider", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_auto_write_forbidden", "providerBinding": "auto_write", "auditEventPrefix": "provider_autowrite_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "provider.autonomous_action", "displayName": "Provider Autonomous Action", "description": "Autonomous provider action without human approval. Permanently forbidden.", "category": "provider", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_autonomous_action_forbidden", "providerBinding": "autonomous_action", "auditEventPrefix": "provider_autonomous_", "metadataSchema": "provider_live_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.read_only_tool", "displayName": "Workflow Step — Read-only Tool", "description": "Workflow step binding a read-only tool.", "category": "workflow", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "read_only_tool", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.fake_provider_roundtrip", "displayName": "Workflow Step — Fake Provider Round-trip", "description": "Workflow step binding the deterministic fake provider round-trip.", "category": "workflow", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "fake_provider_roundtrip", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.sandbox_write_preview", "displayName": "Workflow Step — Sandbox Write Preview", "description": "Workflow step generating a sandbox write preview only (no real write).", "category": "workflow", "status": "enabled", "permissionClass": "WRITE_PREVIEW", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "dry_run", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": true, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "sandbox_write_preview", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.rollback_reference", "displayName": "Workflow Step — Rollback Reference", "description": "Workflow step referencing a rollback manifest (read-only reference).", "category": "workflow", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "rollback_reference", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.manual_note", "displayName": "Workflow Step — Manual Note", "description": "Workflow step carrying a manual operator note (read-only).", "category": "workflow", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "manual_note", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.step.audit_query", "displayName": "Workflow Step — Audit Query", "description": "Workflow step performing a read-only audit query.", "category": "workflow", "status": "enabled", "permissionClass": "READ_ONLY", "trustLevel": "BUILTIN_VERIFIED", "executionMode": "read_only", "routeExposure": "existing_route_only", "requiresApproval": false, "requiresDryRun": false, "requiresConfirmation": false, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": false, "blockedReason": null, "workflowBinding": "audit_query", "auditEventPrefix": "workflow_step_", "metadataSchema": "workflow_step_v1", "redactionApplied": true},
  {"capabilityId": "workflow.write_execute", "displayName": "Workflow Write Execute", "description": "Workflow write execution. Requires separate authorization; not executable until authorized.", "category": "workflow", "status": "blocked", "permissionClass": "WRITE_CONFIRM", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": true, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "workflow_write_execute_requires_separate_authorization", "workflowBinding": "write_execute", "auditEventPrefix": "workflow_write_", "metadataSchema": "workflow_write_v1", "redactionApplied": true},
  {"capabilityId": "workflow.rollback_execute", "displayName": "Workflow Rollback Execute", "description": "Workflow rollback execution. Requires separate authorization; not executable until authorized.", "category": "workflow", "status": "blocked", "permissionClass": "ROLLBACK_CONFIRM", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "workflow_rollback_execute_requires_separate_authorization", "workflowBinding": "rollback_execute", "auditEventPrefix": "workflow_rollback_", "metadataSchema": "workflow_write_v1", "redactionApplied": true},
  {"capabilityId": "workflow.auto_advance", "displayName": "Workflow Auto-advance", "description": "Autonomous workflow step auto-advancement. Permanently forbidden.", "category": "workflow", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "workflow_auto_advance_forbidden", "workflowBinding": "auto_advance", "auditEventPrefix": "workflow_autoadvance_", "metadataSchema": "workflow_write_v1", "redactionApplied": true},
  {"capabilityId": "workflow.autonomous_write", "displayName": "Workflow Autonomous Write", "description": "Autonomous workflow write without human approval. Permanently forbidden.", "category": "workflow", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "workflow_autonomous_write_forbidden", "workflowBinding": "autonomous_write", "auditEventPrefix": "workflow_autonomous_", "metadataSchema": "workflow_write_v1", "redactionApplied": true},
  {"capabilityId": "workflow.background_schedule", "displayName": "Workflow Background Schedule", "description": "Background / unsupervised workflow scheduling. Permanently forbidden.", "category": "workflow", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXPERIMENTAL_DISABLED", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "workflow_background_schedule_forbidden", "workflowBinding": "background_schedule", "auditEventPrefix": "workflow_background_", "metadataSchema": "workflow_write_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.dynamic_plugin_load", "displayName": "Forbidden — Dynamic Plugin Load", "description": "Dynamic plugin / importlib / path-based code loading. Described as blocked; never loaded.", "category": "registry", "status": "blocked", "permissionClass": "EXTERNAL_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "dynamic_plugin_load_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.remote_registry", "displayName": "Forbidden — Remote Registry", "description": "Remote registry / remote manifest fetch. Described as blocked; never fetched.", "category": "registry", "status": "blocked", "permissionClass": "EXTERNAL_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "remote_registry_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.marketplace", "displayName": "Forbidden — Marketplace", "description": "Plugin marketplace. Described as blocked; never reachable.", "category": "registry", "status": "blocked", "permissionClass": "EXTERNAL_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "marketplace_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.shell", "displayName": "Forbidden — Shell", "description": "Shell-command capability. Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "shell_command_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.database_mutation", "displayName": "Forbidden — Database Mutation", "description": "Database mutation capability. Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "database_mutation_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.external_http", "displayName": "Forbidden — External HTTP", "description": "External HTTP capability. Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "EXTERNAL_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "external_http_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.production_operation", "displayName": "Forbidden — Production Operation", "description": "Production operation against the production home or production database. Described as blocked; never reached.", "category": "registry", "status": "blocked", "permissionClass": "PRODUCTION_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "production_operation_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.provider_write", "displayName": "Forbidden — Provider Write", "description": "Provider write (alias declaration). Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_write_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.provider_auto_write", "displayName": "Forbidden — Provider Auto-write", "description": "Provider auto-write (alias declaration). Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "provider_auto_write_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
  {"capabilityId": "capability.forbidden.autonomous_write", "displayName": "Forbidden — Autonomous Write", "description": "Autonomous write (alias declaration). Described as blocked; never executed.", "category": "registry", "status": "blocked", "permissionClass": "ADMIN_FORBIDDEN", "trustLevel": "EXTERNAL_FORBIDDEN", "executionMode": "none", "routeExposure": "forbidden_new_route", "requiresApproval": true, "requiresDryRun": false, "requiresConfirmation": true, "requiresAudit": true, "requiresBudget": false, "requiresKillSwitch": false, "devOnly": true, "productionAllowed": false, "disabledByDefault": true, "blockedReason": "autonomous_write_forbidden", "auditEventPrefix": "capability_forbidden_", "metadataSchema": "forbidden_v1", "redactionApplied": true},
]

// Forbidden field set — the mirror must never carry any of these.
export const CAPABILITY_FORBIDDEN_FIELDS = [
  "pythonImportPath",
  "callable",
  "shellCommand",
  "externalUrl",
  "downloadUrl",
  "pluginPackage",
  "dynamicModule",
  "evalCode",
  "execCode",
  "sqlStatement",
  "productionPath",
  "apiKey",
  "Authorization",
  "secret",
] as const
