/**
 * Frozen static Plugin Descriptor Registry manifest — Phase 3D (frontend mirror).
 *
 * This is a tracked, reviewable, deterministic mirror of the backend static
 * manifest (hermes_cli/dev_web_plugin_descriptor_manifest.py). It carries
 * ONLY safe, value-free fields — no API key, Authorization, Bearer, secret,
 * callable repr, shell command, SQL statement, production path, local plugin
 * path, dynamic import path, external URL, download URL, or install command.
 *
 * The authoritative runtime validation status + counts come from the live
 * GET /status data.pluginDescriptorRegistry block; this constant provides the
 * read-only list + detail (no new HTTP route is introduced). The registry
 * describes future plugin descriptors only — it never grants permission, never
 * loads a plugin, never executes a plugin. No plugin runtime, no plugin loader,
 * no dynamic loading, no local plugin directory loading, no remote registry /
 * marketplace / external plugin fetch.
 */

import type { PluginDescriptorDetail } from '@/types/api/pluginDescriptorRegistry'

export const PLUGIN_DESCRIPTOR_REGISTRY_VERSION = 'phase3d-static-descriptor-v1'

export const PLUGIN_DESCRIPTOR_MANIFEST: readonly PluginDescriptorDetail[] = [
  {
    pluginId: 'plugin.descriptor.registry_status',
    displayName: 'Plugin Descriptor Registry Status',
    description:
      'Read-only plugin descriptor registry summary surfaced under the existing /status block. Descriptor only — does not execute a plugin.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'builtin_static',
    trustLevel: 'trusted_static_descriptor',
    status: 'visible',
    capabilityBindings: ['registry.capability_registry_status'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_status_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.capability_binding_view',
    displayName: 'Plugin Descriptor Capability Binding View',
    description:
      'Read-only view of how plugin descriptors bind to Phase 3C capabilityIds. Descriptor only — does not execute a plugin or grant permission.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'trusted_static_descriptor',
    status: 'visible',
    capabilityBindings: ['registry.capability_registry_detail'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_binding_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.audit_view',
    displayName: 'Plugin Descriptor Audit View',
    description:
      'Read-only view of redacted plugin_descriptor_* audit breadcrumbs (safe fields only). Descriptor only — does not execute a plugin.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'trusted_static_descriptor',
    status: 'visible',
    capabilityBindings: ['registry.capability_registry_audit'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_audit_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.read_only_tool_bridge',
    displayName: 'Plugin Descriptor Read-only Tool Bridge',
    description:
      'Descriptor-only bridge to read-only tool capabilities. Disabled by default — does not execute a tool, does not grant permission.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'dev_reviewed_descriptor',
    status: 'disabled',
    capabilityBindings: ['tool.read.tool_policy_read', 'tool.read.route_governance_read'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_tool_bridge_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.sandbox_write_preview_bridge',
    displayName: 'Plugin Descriptor Sandbox Write-preview Bridge',
    description:
      'Descriptor-only bridge to dev-sandbox write capabilities. Inherits WRITE_CONFIRM; disabled by default; never performs a real write.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'dev_reviewed_descriptor',
    status: 'disabled',
    capabilityBindings: [
      'tool.sandbox.dev_sandbox_file_write',
      'tool.sandbox.dev_sandbox_file_append',
      'tool.sandbox.dev_sandbox_file_patch',
    ],
    permissionClass: 'WRITE_CONFIRM',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: true,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_sandbox_bridge_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.provider_boundary_bridge',
    displayName: 'Plugin Descriptor Provider Boundary Bridge',
    description:
      'Descriptor-only bridge to the real-provider boundary (read-only). Disabled by default — does not call a provider, does not grant permission.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'dev_reviewed_descriptor',
    status: 'disabled',
    capabilityBindings: ['provider.real_boundary_status', 'provider.real_request_preview'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_provider_bridge_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.workflow_step_bridge',
    displayName: 'Plugin Descriptor Workflow Step Bridge',
    description:
      'Descriptor-only bridge to read-only workflow steps. Disabled by default — does not advance a workflow, does not grant permission.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'tracked_static_descriptor',
    trustLevel: 'dev_reviewed_descriptor',
    status: 'disabled',
    capabilityBindings: ['workflow.step.read_only_tool', 'workflow.step.manual_note'],
    permissionClass: 'READ_ONLY',
    executionMode: 'descriptor_only',
    requiresApproval: false,
    requiresDryRun: false,
    requiresConfirmation: false,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: null,
    metadataSchema: 'plugin_descriptor_workflow_bridge_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.dynamic_plugin_load_blocked',
    displayName: 'Blocked — Dynamic Plugin Load',
    description:
      'Descriptor declaring dynamic plugin / importlib / path-based loading as permanently blocked. Described only; never loaded.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'external_forbidden',
    trustLevel: 'external_forbidden',
    status: 'blocked',
    capabilityBindings: ['capability.forbidden.dynamic_plugin_load'],
    permissionClass: 'EXTERNAL_FORBIDDEN',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: false,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: 'dynamic_plugin_load_is_forbidden',
    metadataSchema: 'plugin_descriptor_forbidden_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.remote_registry_blocked',
    displayName: 'Blocked — Remote Registry',
    description:
      'Descriptor declaring a remote plugin registry / remote manifest fetch as permanently blocked. Described only; never fetched.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'external_forbidden',
    trustLevel: 'external_forbidden',
    status: 'blocked',
    capabilityBindings: ['capability.forbidden.remote_registry'],
    permissionClass: 'EXTERNAL_FORBIDDEN',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: false,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: 'remote_registry_is_forbidden',
    metadataSchema: 'plugin_descriptor_forbidden_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.marketplace_blocked',
    displayName: 'Blocked — Marketplace',
    description:
      'Descriptor declaring a plugin marketplace as permanently blocked. Described only; never reachable.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'external_forbidden',
    trustLevel: 'external_forbidden',
    status: 'blocked',
    capabilityBindings: ['capability.forbidden.marketplace'],
    permissionClass: 'EXTERNAL_FORBIDDEN',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: false,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: 'marketplace_is_forbidden',
    metadataSchema: 'plugin_descriptor_forbidden_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.external_execution_blocked',
    displayName: 'Blocked — External Execution',
    description:
      'Descriptor declaring external execution (shell / database mutation / external HTTP) as permanently blocked. Described only; never executed.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'external_forbidden',
    trustLevel: 'external_forbidden',
    status: 'blocked',
    capabilityBindings: [
      'capability.forbidden.external_http',
      'capability.forbidden.shell',
      'capability.forbidden.database_mutation',
    ],
    permissionClass: 'EXTERNAL_FORBIDDEN',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: false,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: 'external_execution_is_forbidden',
    metadataSchema: 'plugin_descriptor_forbidden_v1',
    redactionApplied: true,
  },
  {
    pluginId: 'plugin.descriptor.production_operation_blocked',
    displayName: 'Blocked — Production Operation',
    description:
      'Descriptor declaring a production operation (production home / production database) as permanently blocked. Described only; never reached.',
    version: PLUGIN_DESCRIPTOR_REGISTRY_VERSION,
    owner: 'phase-3d',
    source: 'production_forbidden',
    trustLevel: 'production_forbidden',
    status: 'blocked',
    capabilityBindings: ['capability.forbidden.production_operation'],
    permissionClass: 'PRODUCTION_FORBIDDEN',
    executionMode: 'descriptor_only',
    requiresApproval: true,
    requiresDryRun: false,
    requiresConfirmation: true,
    requiresAudit: true,
    requiresBudget: false,
    requiresKillSwitch: false,
    devOnly: true,
    productionAllowed: false,
    disabledByDefault: true,
    blockedReason: 'production_operation_is_forbidden',
    metadataSchema: 'plugin_descriptor_forbidden_v1',
    redactionApplied: true,
  },
]

// Forbidden field set — the mirror must never carry any of these (canonical +
// alias / casing variants), mirroring the backend schema.
export const PLUGIN_FORBIDDEN_FIELDS = [
  'pythonImportPath',
  'callable',
  'shellCommand',
  'externalUrl',
  'downloadUrl',
  'pluginPackage',
  'dynamicModule',
  'evalCode',
  'execCode',
  'sqlStatement',
  'productionPath',
  'apiKey',
  'Authorization',
  'secret',
  'localPath',
  'remoteUrl',
  'installCommand',
  'postInstallHook',
  'preExecutionHook',
  'arbitraryArgs',
  'authorization',
  'bearer',
  'Bearer',
  'api_key',
  'secretValue',
  'token',
  'accessToken',
  'callable_repr',
  'shell_command',
  'sql',
  'production_path',
  'dynamic_import',
  'importPath',
  'modulePath',
  'external_url',
  'download_url',
  'install_command',
  'post_install_hook',
  'pre_execution_hook',
] as const
